// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/features/profile/presentation/view_model/profile_cubit/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/core/base/api_result.dart' as _i5;
import 'package:tracking_app/features/profile/data/model/get_logged_driver_data_response.dart'
    as _i6;
import 'package:tracking_app/features/profile/data/model/get_vehicle_response.dart'
    as _i9;
import 'package:tracking_app/features/profile/domain/repos/profile_repo.dart'
    as _i2;
import 'package:tracking_app/features/profile/domain/use_case/get_logged_driver_data_use_case.dart'
    as _i3;
import 'package:tracking_app/features/profile/domain/use_case/get_vechile_name_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileRepo_0 extends _i1.SmartFake implements _i2.ProfileRepo {
  _FakeProfileRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLoggedDriverDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLoggedDriverDataUseCase extends _i1.Mock
    implements _i3.GetLoggedDriverDataUseCase {
  MockGetLoggedDriverDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  set profileRepo(_i2.ProfileRepo? _profileRepo) => super.noSuchMethod(
    Invocation.setter(#profileRepo, _profileRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.GetLoggedDriverDataResponse>> invoke() =>
      (super.noSuchMethod(
            Invocation.method(#invoke, []),
            returnValue: _i4.Future<
              _i5.ApiResult<_i6.GetLoggedDriverDataResponse>
            >.value(
              _i7.dummyValue<_i5.ApiResult<_i6.GetLoggedDriverDataResponse>>(
                this,
                Invocation.method(#invoke, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.GetLoggedDriverDataResponse>>);
}

/// A class which mocks [GetVechileNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVechileNameUseCase extends _i1.Mock
    implements _i8.GetVechileNameUseCase {
  MockGetVechileNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  set profileRepo(_i2.ProfileRepo? _profileRepo) => super.noSuchMethod(
    Invocation.setter(#profileRepo, _profileRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i9.GetVehicleResponse>> invoke(String? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [vehicleId]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i9.GetVehicleResponse>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i9.GetVehicleResponse>>(
                    this,
                    Invocation.method(#invoke, [vehicleId]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i9.GetVehicleResponse>>);
}
