// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/features/home/data/repo/home_screen_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/core/base/api_result.dart' as _i5;
import 'package:tracking_app/features/home/data/data%20source/home_screen_data_source.dart'
    as _i3;
import 'package:tracking_app/features/home/data/models/pending_orders_response.dart'
    as _i6;
import 'package:tracking_app/features/orders/data/model/orders_firebase_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrdersFirebaseModel_0 extends _i1.SmartFake
    implements _i2.OrdersFirebaseModel {
  _FakeOrdersFirebaseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeScreenDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeScreenDataSource extends _i1.Mock
    implements _i3.HomeScreenDataSource {
  MockHomeScreenDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>> getAllPendingOrders(
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPendingOrders, [page]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i6.PendingOrderResponse>>(
                    this,
                    Invocation.method(#getAllPendingOrders, [page]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>>);

  @override
  _i4.Future<_i2.OrdersFirebaseModel> getOrderDetailsFireBase() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetailsFireBase, []),
            returnValue: _i4.Future<_i2.OrdersFirebaseModel>.value(
              _FakeOrdersFirebaseModel_0(
                this,
                Invocation.method(#getOrderDetailsFireBase, []),
              ),
            ),
          )
          as _i4.Future<_i2.OrdersFirebaseModel>);

  @override
  _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>> startOrder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [id]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i6.PendingOrderResponse>>(
                    this,
                    Invocation.method(#startOrder, [id]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>>);
}
