// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/features/auth/login/data/repository_implementation/login_repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/core/base/api_result.dart' as _i4;
import 'package:tracking_app/features/auth/login/data/data_source/login_remote_data_source.dart'
    as _i2;
import 'package:tracking_app/features/auth/login/data/model/login_request.dart'
    as _i6;
import 'package:tracking_app/features/auth/login/data/model/login_response.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRemoteDataSource extends _i1.Mock
    implements _i2.LoginRemoteDataSource {
  MockLoginRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginResponse>> login({
    required _i6.LoginRequest? loginRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequest: loginRequest}),
            returnValue: _i3.Future<_i4.ApiResult<_i5.LoginResponse>>.value(
              _i7.dummyValue<_i4.ApiResult<_i5.LoginResponse>>(
                this,
                Invocation.method(#login, [], {#loginRequest: loginRequest}),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.LoginResponse>>);
}
