// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOUTN4yiBvimfcv6qn5J-V6AcKwWKjFFg',
    appId: '1:391214810716:web:fa499c4d863f568188c899',
    messagingSenderId: '391214810716',
    projectId: 'traking-app-57b68',
    authDomain: 'traking-app-57b68.firebaseapp.com',
    storageBucket: 'traking-app-57b68.firebasestorage.app',
    measurementId: 'G-RCYZPE6CEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-aiJTivVnithcUR2Ds-5FgH5W1nfznq8',
    appId: '1:391214810716:android:a5dbf00b0a96b5e188c899',
    messagingSenderId: '391214810716',
    projectId: 'traking-app-57b68',
    storageBucket: 'traking-app-57b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4S_qrHvtPOlnL90EOH76vGaqHujYg38',
    appId: '1:391214810716:ios:8ddba4af6e22d01f88c899',
    messagingSenderId: '391214810716',
    projectId: 'traking-app-57b68',
    storageBucket: 'traking-app-57b68.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4S_qrHvtPOlnL90EOH76vGaqHujYg38',
    appId: '1:391214810716:ios:8ddba4af6e22d01f88c899',
    messagingSenderId: '391214810716',
    projectId: 'traking-app-57b68',
    storageBucket: 'traking-app-57b68.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOUTN4yiBvimfcv6qn5J-V6AcKwWKjFFg',
    appId: '1:391214810716:web:351c3e268d3511e688c899',
    messagingSenderId: '391214810716',
    projectId: 'traking-app-57b68',
    authDomain: 'traking-app-57b68.firebaseapp.com',
    storageBucket: 'traking-app-57b68.firebasestorage.app',
    measurementId: 'G-354M60P69S',
  );

}