// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/features/auth/forget_password/data/data_source/forget_password_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/core/api_manger/api_service.dart' as _i4;
import 'package:tracking_app/features/auth/forget_password/data/models/request/forget_password_request.dart'
    as _i6;
import 'package:tracking_app/features/auth/forget_password/data/models/request/otp_request.dart'
    as _i7;
import 'package:tracking_app/features/auth/forget_password/data/models/response/forget_password_response.dart'
    as _i2;
import 'package:tracking_app/features/auth/forget_password/data/models/response/otp_response.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpResponse_1 extends _i1.SmartFake implements _i3.OtpResponse {
  _FakeOtpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ForgetPasswordResponse> forgetPassword(
    _i6.ForgetPasswordRequest? forgetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequest]),
            returnValue: _i5.Future<_i2.ForgetPasswordResponse>.value(
              _FakeForgetPasswordResponse_0(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequest]),
              ),
            ),
          )
          as _i5.Future<_i2.ForgetPasswordResponse>);

  @override
  _i5.Future<_i3.OtpResponse> verifyResetCode(_i7.OtpRequest? otpRequest) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [otpRequest]),
            returnValue: _i5.Future<_i3.OtpResponse>.value(
              _FakeOtpResponse_1(
                this,
                Invocation.method(#verifyResetCode, [otpRequest]),
              ),
            ),
          )
          as _i5.Future<_i3.OtpResponse>);
}
