// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/features/auth/forget_password/data/data_source/forget_password_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dio/dio.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/core/api_manger/api_service.dart' as _i9;
import 'package:tracking_app/features/apply/data/models/apply_model/apply_response/apply_response.dart'
    as _i6;
import 'package:tracking_app/features/apply/data/models/get_all_vehicles_response/get_all_vehicles_response.dart'
    as _i7;
import 'package:tracking_app/features/auth/forget_password/data/models/request/forget_password_request.dart'
    as _i12;
import 'package:tracking_app/features/auth/forget_password/data/models/request/otp_request.dart'
    as _i13;
import 'package:tracking_app/features/auth/forget_password/data/models/request/reset_password_request.dart'
    as _i14;
import 'package:tracking_app/features/auth/forget_password/data/models/response/forget_password_response.dart'
    as _i3;
import 'package:tracking_app/features/auth/forget_password/data/models/response/otp_response.dart'
    as _i4;
import 'package:tracking_app/features/auth/forget_password/data/models/response/reset_password_response.dart'
    as _i5;
import 'package:tracking_app/features/auth/login/data/model/login_request.dart'
    as _i11;
import 'package:tracking_app/features/auth/login/data/model/login_response.dart'
    as _i2;
import 'package:tracking_app/features/home/data/models/pending_orders_response.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpResponse_2 extends _i1.SmartFake implements _i4.OtpResponse {
  _FakeOtpResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponse {
  _FakeResetPasswordResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyResponse_4 extends _i1.SmartFake implements _i6.ApplyResponse {
  _FakeApplyResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllVehiclesResponse_5 extends _i1.SmartFake
    implements _i7.GetAllVehiclesResponse {
  _FakeGetAllVehiclesResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderResponse_6 extends _i1.SmartFake implements _i8.OrderResponse {
  _FakeOrderResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i9.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.LoginResponse> loginUser(_i11.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [loginRequest]),
            returnValue: _i10.Future<_i2.LoginResponse>.value(
              _FakeLoginResponse_0(
                this,
                Invocation.method(#loginUser, [loginRequest]),
              ),
            ),
          )
          as _i10.Future<_i2.LoginResponse>);

  @override
  _i10.Future<_i3.ForgetPasswordResponse> forgetPassword(
    _i12.ForgetPasswordRequest? forgetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequest]),
            returnValue: _i10.Future<_i3.ForgetPasswordResponse>.value(
              _FakeForgetPasswordResponse_1(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequest]),
              ),
            ),
          )
          as _i10.Future<_i3.ForgetPasswordResponse>);

  @override
  _i10.Future<_i4.OtpResponse> verifyResetCode(_i13.OtpRequest? otpRequest) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [otpRequest]),
            returnValue: _i10.Future<_i4.OtpResponse>.value(
              _FakeOtpResponse_2(
                this,
                Invocation.method(#verifyResetCode, [otpRequest]),
              ),
            ),
          )
          as _i10.Future<_i4.OtpResponse>);

  @override
  _i10.Future<_i5.ResetPasswordResponse> resetPassword(
    _i14.ResetPasswordRequest? ResetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [ResetPasswordRequest]),
            returnValue: _i10.Future<_i5.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_3(
                this,
                Invocation.method(#resetPassword, [ResetPasswordRequest]),
              ),
            ),
          )
          as _i10.Future<_i5.ResetPasswordResponse>);

  @override
  _i10.Future<_i6.ApplyResponse> apply(_i15.FormData? formData) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [formData]),
            returnValue: _i10.Future<_i6.ApplyResponse>.value(
              _FakeApplyResponse_4(this, Invocation.method(#apply, [formData])),
            ),
          )
          as _i10.Future<_i6.ApplyResponse>);

  @override
  _i10.Future<_i7.GetAllVehiclesResponse> getAllVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllVehicles, []),
            returnValue: _i10.Future<_i7.GetAllVehiclesResponse>.value(
              _FakeGetAllVehiclesResponse_5(
                this,
                Invocation.method(#getAllVehicles, []),
              ),
            ),
          )
          as _i10.Future<_i7.GetAllVehiclesResponse>);

  @override
  _i10.Future<_i8.OrderResponse> getAllPendingOrders(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPendingOrders, [page]),
            returnValue: _i10.Future<_i8.OrderResponse>.value(
              _FakeOrderResponse_6(
                this,
                Invocation.method(#getAllPendingOrders, [page]),
              ),
            ),
          )
          as _i10.Future<_i8.OrderResponse>);
}
