// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/home/presentation/view%20model/order_details_firebase_cubit/order_details_firebase_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_app/features/home/data/models/order_response.dart'
    as _i3;
import 'package:tracking_app/features/home/domain/repo/home_repo.dart' as _i2;
import 'package:tracking_app/features/home/domain/use_case/get_orderdetails_from_firebase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepo_0 extends _i1.SmartFake implements _i2.HomeRepo {
  _FakeHomeRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderResponse_1 extends _i1.SmartFake implements _i3.OrderResponse {
  _FakeOrderResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetOrderdetailsFromFirebase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrderdetailsFromFirebase extends _i1.Mock
    implements _i4.GetOrderdetailsFromFirebase {
  MockGetOrderdetailsFromFirebase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepo get homeScreenRepo =>
      (super.noSuchMethod(
            Invocation.getter(#homeScreenRepo),
            returnValue: _FakeHomeRepo_0(
              this,
              Invocation.getter(#homeScreenRepo),
            ),
          )
          as _i2.HomeRepo);

  @override
  set homeScreenRepo(_i2.HomeRepo? value) => super.noSuchMethod(
    Invocation.setter(#homeScreenRepo, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.OrderResponse> invoke() =>
      (super.noSuchMethod(
            Invocation.method(#invoke, []),
            returnValue: _i5.Future<_i3.OrderResponse>.value(
              _FakeOrderResponse_1(this, Invocation.method(#invoke, [])),
            ),
          )
          as _i5.Future<_i3.OrderResponse>);
}
