// Mocks generated by Mockito 5.4.6 from annotations
// in tracking_app/test/features/home/domain/use_case/get_all_pending_orders_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/core/base/api_result.dart' as _i5;
import 'package:tracking_app/features/home/data/data%20source/home_screen_data_source_imp.dart'
    as _i8;
import 'package:tracking_app/features/home/data/models/order_response.dart'
    as _i2;
import 'package:tracking_app/features/home/data/models/pending_orders_response.dart'
    as _i6;
import 'package:tracking_app/features/home/domain/repo/home_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrderResponse_0 extends _i1.SmartFake implements _i2.OrderResponse {
  _FakeOrderResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i3.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>> getAllPendingOrders(
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPendingOrders, [page]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i6.PendingOrderResponse>>(
                    this,
                    Invocation.method(#getAllPendingOrders, [page]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i6.PendingOrderResponse>>);

  @override
  _i4.Future<_i2.OrderResponse> getOrderDetailsFromFireBase() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetailsFromFireBase, []),
            returnValue: _i4.Future<_i2.OrderResponse>.value(
              _FakeOrderResponse_0(
                this,
                Invocation.method(#getOrderDetailsFromFireBase, []),
              ),
            ),
          )
          as _i4.Future<_i2.OrderResponse>);

  @override
  _i4.Future<_i5.ApiResult<void>> acceptOrder({
    required _i8.AcceptOrderRequestEntity? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOrder, [], {#request: request}),
            returnValue: _i4.Future<_i5.ApiResult<void>>.value(
              _i7.dummyValue<_i5.ApiResult<void>>(
                this,
                Invocation.method(#acceptOrder, [], {#request: request}),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<void>>);
}
